version: '3.8'

services:
  # 1. Supabase/PostgreSQL (Primary DB - Users, Projects, RBAC)
  # NOTE: A full Supabase stack is complex. We use a minimal PostgreSQL container here for dev.
  # For the full Supabase experience (Auth, Storage), you would use the Supabase CLI setup.
  postgres:
    image: postgres:15-alpine
    container_name: collide_supabase_db
    environment:
      POSTGRES_USER: collide_db_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: collide_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. MongoDB (Secondary DB - Chat History)
  mongodb:
    image: mongo:latest
    container_name: collide_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: collide_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # 3. Redis (Caching and WebSocket Session Management)
  redis:
    image: redis:latest
    container_name: collide_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # 4. Spring Boot Backend (Development/Testing Environment)
  # This service will run your compiled server-springboot application
  # You need to manually create the Dockerfile for the Spring Boot application first!
  backend:
    build: 
      context: ../../server-springboot # Build from the Spring Boot directory
      dockerfile: Dockerfile           # Assuming you place a Dockerfile here later
    container_name: collide_backend
    ports:
      - "8080:8080" # Spring Boot default port
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      # These variables allow Spring Boot to connect to the other services
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collide_db
      SPRING_DATA_MONGODB_URI: mongodb://<YOUR_MONGO_ROOT_USER>:<YOUR_MONGO_ROOT_PASSWORD>@mongodb:27017/
      SPRING_REDIS_HOST: redis
    restart: always

volumes:
  postgres_data:
  mongo_data:
  redis_data: